# Generated by Django 5.0.2 on 2024-03-15 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('pricing', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_charging_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_status', models.CharField(max_length=50)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_server.chargingstation')),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_server.connectortype')),
            ],
        ),
    ]
