# Generated by Django 4.1.13 on 2024-03-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev_server', '0003_chargingstation_balance_chargingstation_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
