# Generated by Django 4.1.13 on 2024-03-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev_server', '0004_chargingstation_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='max_charging_power',
        ),
    ]
